In [1]:
# ===== درس ۶: NumPy پایه =====

# ۱. اتصال Google Drive
from google.colab import drive
drive.mount('/content/drive')

# ۲. تعریف مسیرهای پروژه با pathlib
from pathlib import Path

PROJECT = Path("/content/drive/MyDrive/scRNA_project")
LESSON = PROJECT / "lesson06"

CODE = LESSON / "code"
NOTES = LESSON / "notes"
OUTPUT = LESSON / "output"

# ۳. ساخت پوشه‌های همین درس
for folder in [CODE, NOTES, OUTPUT]:
    folder.mkdir(parents=True, exist_ok=True)
    print("آماده شد:", folder)

# ۴. نصب Scanpy (فقط در صورت نیاز)
!pip install scanpy -q

# ۵. وارد کردن کتابخونه‌ها
import scanpy as sc
import numpy as np

# ۶. بارگذاری دیتاست PBMC-3k
adata = sc.datasets.pbmc3k()

Mounted at /content/drive
آماده شد: /content/drive/MyDrive/scRNA_project/lesson06/code
آماده شد: /content/drive/MyDrive/scRNA_project/lesson06/notes
آماده شد: /content/drive/MyDrive/scRNA_project/lesson06/output
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 31.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.8/188.8 kB 16.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.0/40.0 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 77.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.7/363.7 kB 19.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 76.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 4.7 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the p

  0%|          | 0.00/5.58M [00:00<?, ?B/s]

In [2]:
# ۵. یک آرایه‌ی ساختگی کوچک برای تمرین NumPy (۳ سلول × ۳ ژن فرضی)
arr = np.array([
    [5, 0, 12],
    [3, 8, 0],
    [0, 2, 7]
])

arr

array([[ 5,  0, 12],
       [ 3,  8,  0],
       [ 0,  2,  7]])

In [4]:
# ۶. نوع Object و ابعاد آرایه
type(arr)
arr.shape

(3, 3)

In [5]:
# ۷. ایندکس‌گذاری روی آرایه‌ی ساختگی
arr[0]        # سطر اول
arr[0, 0]     # یک خانه‌ی مشخص
arr[:, 0]     # ستون اول

array([5, 3, 0])

In [6]:
# ۸. عملیات ریاضی روی کل آرایه (بدون for دستی)
arr.sum()
arr.sum(axis=0)
arr.sum(axis=1)
arr.mean()

np.float64(4.111111111111111)

In [7]:
# ۹. یک تکه‌ی کوچک و امن از adata.X واقعی (۵ سلول × ۵ ژن اول)
small_piece = adata.X[:5, :5].toarray()

type(small_piece)
small_piece

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [8]:
# ۱۰. همان محاسبه‌ی axis روی داده‌ی واقعی
small_piece.sum(axis=1)

array([0., 0., 0., 0., 0.], dtype=float32)